[package]
name = "firestore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
firestore_grpc = "0.109"
tokio = {version = "1.0", features = ["full"]}